name: Test Directories Loop

on:
  push:
    paths:
      - '.github/workflows/loops-test.yml'

env:
  VALUES: "value1/THIS,value2,value3"

jobs:
  example_job:
    runs-on: ubuntu-latest
    
    env:
      MY_VALUES: "value1,value2,value3"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Use delimited string as an array
        run: |
          IFS=',' read -r -a my_array <<< ${{ env.VALUES }}
          for element in "${my_array[@]}"
          do
            echo "$element"
          done