name: CI
on:
  push:
    paths:
      - '.github/workflows/one-more-test-ms-container.yml'

env:
  COMPANY: "Illumina, Inc"
  CONFIG_SIGN_ENFORCED: false
  FIRST_PUBLISH_YEAR: 2024

jobs:
  container-check-variables:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/dotnet/core/sdk:3.1.201
      options: --rm

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Read Version from File
      id: read_version
      run: |
        VERSION=$(cat build/VERSION)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Set build environment variables
      id: set-vars
      run: |
        if [ "${{ env.CONFIG_SIGN_ENFORCED }}" = "false" ]; then
          echo "SECURE_TAG=insecure" >> $GITHUB_ENV
          echo "RELEASE=0.insecure" >> $GITHUB_ENV
          echo "DIST_DIR=insecure" >> $GITHUB_ENV
        else
          echo "RELEASE=0" >> $GITHUB_ENV
          echo "DIST_DIR=secure" >> $GITHUB_ENV
        fi        

    - name: Set copyright
      id: set-copyright-full
      run: |
        COPYRIGHT_SYMBOL="©"
        COMPANY=${{ env.COMPANY }}
        COPYRIGHT_YEAR=${{ env.COPYRIGHT_YEAR }}
        COPYRIGHT="$COPYRIGHT_SYMBOL $COPYRIGHT_YEAR $COMPANY All Rights Reserved."
        echo "before"
        echo "COPYRIGHT=$COPYRIGHT" >> $GITHUB_ENV 
        echo "after"
