name: Run tests on MS container
on:
  workflow_dispatch:  
  push:
    paths:
      - '.github/workflows/one-more-test-ms-container.yml'

jobs:
  container-dotnet-pack:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/core/sdk:3.1.201
      options: --rm

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
        
    - name: Install NuGet CLI
      shell: bash
      run: |
        apt update
        apt install nuget -y
        nuget --version
        nuget --help

      
    