name: Tag Release

on:
  push:
    paths:
      - '.github/workflows/test-versions-with-tags.yml'


jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get tags matching v*.*.*
      id: get_matching_tags
      run: |
        # Get all tags that match the pattern v*.*.*
        MATCHING_TAGS=$(git tag -l 'v*.*.*')
        if [ -z "$MATCHING_TAGS" ]; then
          echo "No tags matching the pattern v*.*.* found"
        else
          echo "MATCHING_TAGS=$MATCHING_TAGS" >> $GITHUB_ENV
        fi


    - name: Increment minor version
      id: increment_version
      run: |
        LATEST_TAG=${{ env.LATEST_TAG }}
        VERSION=${LATEST_TAG#v}
        IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
        MINOR=$((MINOR + 1))
        PATCH=0
        echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
        echo $MAJOR
        echo $MINOR
        echo $PATCH
        NEW_TAG="v$MAJOR.$MINOR.0"
        echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

    - name: Configure Git
      run: |
        git config --global user.name 'Garret Coffman'
        git config --global user.email 'garret.coffman2023@gmail.com'

    - name: Display Git info
      run: |
        git status
        git tag -l

    - name: Push new tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Create a new annotated tag
        git tag -a $NEW_TAG -m "Bump version to $NEW_TAG"
        # Push the new tag to the repository
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} $NEW_TAG