name: Tag Release

on:
  push:
    paths:
      - '.github/workflows/test-versions-with-tags.yml'
    tags:
      - 'v*.*.*'  # Match tags of the form vX.X.X

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get version from tag
      id: get_version
      run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

    - name: Display version
      run: echo "The version is $VERSION"

    - name: Increment version
      id: increment_version
      run: |
        IFS='.' read -r MAJOR MINOR PATCH <<< "${LATEST_TAG#v}"
        PATCH=$((PATCH + 1)) # Increment patch version
        NEW_TAG="v$MAJOR.$MINOR.$PATCH"
        echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

    - name: Create new tag
      run: |
        git tag -a $NEW_TAG -m "Bump version to $NEW_TAG"
        git push origin $NEW_TAG

    - name: Push new tag
      run: |
        git push origin $NEW_TAG