name: Tag Release

on:
  push:
    paths:
      - '.github/workflows/test-versions-with-tags.yml'


jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Fetch all tags
      run: |
        git fetch --tags

    - name: Get most recent version tag
      id: get_version_tag
      run: |
        # Define the version tag pattern
        VERSION_PATTERN='v*.*.*'
        
        # Get all tags matching the version pattern and sort them
        LATEST_TAG=$(git tag -l "$VERSION_PATTERN" --sort=-v:refname | head -n 1)
        
        # If no tag matches the pattern, default to "v0.0.0"
        if [ -z "$LATEST_TAG" ]; then
          LATEST_TAG="v0.0.0"
        fi
        
        echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

    - name: Echo LATEST_TAG
      run: |
        echo "LATEST_TAG is: ${{ env.LATEST_TAG }}"
    - name: Increment minor version
      id: increment_version
      run: |
        LATEST_TAG=${{ env.LATEST_TAG }}
        VERSION=${LATEST_TAG#v}
        IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
        MINOR=$((MINOR + 1))
        PATCH=0
        echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
        echo $MAJOR
        echo $MINOR
        echo $PATCH
        NEW_TAG="v$MAJOR.$MINOR.0"
        echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

    - name: Configure Git
      run: |
        git config --global user.name 'Garret Coffman'
        git config --global user.email 'garret.coffman2023@gmail.com'

    - name: Display Git info
      run: |
        git status
        git tag -l

    - name: Push new tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Create a new annotated tag
        git tag -a $NEW_TAG -m "Bump version to $NEW_TAG"
        # Push the new tag to the repository
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} $NEW_TAG