name: Tag Release

on:
  push:
    paths:
      - '.github/workflows/test-versions-with-tags.yml'


jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get latest tag
      id: get_latest_tag
      run: |
        git fetch --tags
        git tag -l
        LATEST_TAG=$(git describe --tags --match "v*" --abbrev=0 --always)
        echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

    - name: Increment minor version
      id: increment_version
      run: |
        LATEST_TAG=${LATEST_TAG#v}
        IFS='.' read -r MAJOR MINOR PATCH <<< "$LATEST_TAG"
        MINOR=$((MINOR + 1))
        NEW_TAG="v$MAJOR.$MINOR.0"
        echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

    - name: Create and push new tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git tag -a $NEW_TAG -m "Bump version to $NEW_TAG"
        git push origin $NEW_TAG