name: Tag Release

on:
  push:
    paths:
      - '.github/workflows/test-versions-with-tags.yml'


jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get latest tag
      id: get_latest_tag
      run: |
        LATEST_TAG=$(git tag -l "v*" --sort=-v:refname | head -n 1)
        if [ -z "$LATEST_TAG" ]; then
          LATEST_TAG="v1.0.0"
        fi
        echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
        echo $LATEST_TAG


    - name: Increment minor version
      id: increment_version
      run: |
        LATEST_TAG=${LATEST_TAG#v}
        IFS='.' read -r MAJOR MINOR PATCH <<< "${{ env.LATEST_TAG }}"
        MINOR=$((MINOR + 1))
        echo $MAJOR
        echo $MINOR
        echo $PATCH
        NEW_TAG="v$MAJOR.$MINOR.0"
        echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

    - name: Create and push new tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git tag -a $NEW_TAG -m "Bump version to $NEW_TAG"
        git push origin $NEW_TAG