on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/your-workflow-file.yml'

jobs:
  increment_version:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get current version
      id: get_version
      run: |
        version=$(git describe --tags `git rev-list --tags --max-count=1`)
        echo "Current version: $version"
        echo "::set-output name=version::$version"
    
 